version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    labels:
      - "Type: Maintenance"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      labels:
        - "Type: Maintenance"
